#!/usr/bin/env python3
"""Turn a raw 6502 binary into a Rust module for the firmware's built-in demo.

usage: bin2rs.py PROGRAM.bin LOAD_ADDR > src/demo_program.rs
"""
import os
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__.strip())

path = sys.argv[1]
addr = int(sys.argv[2].lstrip("$"), 16)
with open(path, "rb") as f:
    data = f.read()

print(f"//! Generated by tools/bin2rs.py from {os.path.basename(path)}; do not edit.")
print()
print("/// Where the built-in demo is loaded and started.")
print(f"pub const DEMO_LOAD_ADDR: u16 = 0x{addr:04X};")
print()
print("/// The built-in demo, assembled from `asm/hello.asm`.")
print("#[rustfmt::skip]")
print("pub const DEMO_PROGRAM: &[u8] = &[")
for i in range(0, len(data), 12):
    print("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 12]) + ",")
print("];")
